openapi: 3.0.0
info:
  title: Minha API Express
  version: 1.0.0
  description: Documentação da API Express com Swagger
servers:
  - url: 'http://localhost:5000'
    description: Servidor de Desenvolvimento
paths:
  /example:
    get:
      summary: Exemplo de endpoint
      responses:
        '200':
          description: Operação bem-sucedida
